# Generated by Django 2.1.5 on 2019-01-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeystrokeDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default=None, max_length=30)),
                ('sentence_index', models.IntegerField(default=0)),
                ('chr0_up', models.IntegerField(default=0)),
                ('chr0_dn', models.IntegerField(default=0)),
                ('chr1_up', models.IntegerField(default=0)),
                ('chr1_dn', models.IntegerField(default=0)),
                ('chr2_up', models.IntegerField(default=0)),
                ('chr2_dn', models.IntegerField(default=0)),
                ('chr3_up', models.IntegerField(default=0)),
                ('chr3_dn', models.IntegerField(default=0)),
                ('chr4_up', models.IntegerField(default=0)),
                ('chr4_dn', models.IntegerField(default=0)),
                ('chr5_up', models.IntegerField(default=0)),
                ('chr5_dn', models.IntegerField(default=0)),
                ('chr6_up', models.IntegerField(default=0)),
                ('chr6_dn', models.IntegerField(default=0)),
                ('chr7_up', models.IntegerField(default=0)),
                ('chr7_dn', models.IntegerField(default=0)),
                ('chr8_up', models.IntegerField(default=0)),
                ('chr8_dn', models.IntegerField(default=0)),
                ('chr9_up', models.IntegerField(default=0)),
                ('chr9_dn', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='user_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default=None, max_length=30)),
                ('index', models.IntegerField(default=0)),
            ],
        ),
    ]
